### ISSUE TITLE
I

### ISSUE THREAD

**Issue by tonyriverms** [GemsLab/REGAL#10]

**Comment by markheimann** [comment]
Hey, sorry to hear about this.  The first thing I would say is check the Python version—this one was tested with Python 2.7.16, and I was recently informed that the code may have an issue with other Python versions.  (I have to look into this soon.)  

Regarding your other two points:   

1.  Interesting point.  We found for this application it didn’t make much difference (we tried several other graph-based heuristics for selecting landmarks), so we stuck with the simplest approach.  In the matrix approximation literature, uniform sampling is a competitive technique although there are methods with stronger theoretical guarantees.  Note that in our followup work at KDD ’19 <https://dl.acm.org/doi/abs/10.1145/3292500.3330735>, where we extended the embedding method to use in another applied graph mining task, we actually did find it helpful to use another heuristic to select landmarks.    
2.  Computation for node identity extraction is localized in the network.  Linear runtime in the number of edges is reasonable to expect and what we find empirically.  Just to give another example from elsewhere in the literature,  the concurrent structural node embedding method GraphWave <https://www-cs.stanford.edu/~jure/pubs/graphwave-kdd18.pdf> also reports linear runtime in the number of edges for its $k$-order approximation.  


Best,
Mark
