### ISSUE TITLE
Where can I find the complete datasets of different networks mentioned in the paper?

### ISSUE THREAD

**Issue by Weifanwong** [GemsLab/REGAL#2]
Specially the the Arenas email network with 1% noise, how can I get the same dataset with other percent of noise like 5%...?

**Comment by markheimann** [comment]
Hi Weifan,

You can get the dataset from the Koblenz Network collection (http://konect.uni-koblenz.de/networks/arenas-email <http://konect.uni-koblenz.de/networks/arenas-email>), and basically remove some of the edges with the desired probability.  (You may want to avoid leaving any node completely disconnected.). The format provided in our simple reference example illustrates the kind of format our code accepts, although that could of course be modified.  


Best,
Mark

**Comment by Weifanwong** [comment]
Hi Mark, sorry to reply you so late... But it's really nice of you recommend me this website which helps me a lot. I have been confused for a long time by the source of datasets.

Anyway thanks again for your help. And this paper (REGAL) is really nice too.

Best wishes,
Weifan
