### ISSUE TITLE
I am confused with the dataset arenas.

### ISSUE THREAD

**Issue by ChenBaiyang** [GemsLab/REGAL#7]
Dear Authors,

I found from the anchor pairs file: "arenas_edges-mapping-permutation.txt" , see below records:
------------------------------------------------------------------------------------
>>> anchor = pickle.load(open('data/arenas_edges-mapping-permutation.txt','rb'))
>>> anchor[0]
334
>>> anchor[334]
1120
>>> anchor[1120]
1103
------------------------------------------------------------------------------------
Does it mean the pairs (0,334), (334,1120), (1120,1103)..... are all anchors ?

Also, I found the from the edge list file "arenas_combined_edges.txt", there are 2270 nodes totally (node ids range from 0 to 2269),  and there are 1135 pairs of anchors, but all the anchor node ids are range from 0 to 1134, no one is in the range from 1135 to 2269. 

Could you please help to make it clear? 

Regards,
Bryan Chen

**Comment by markheimann** [comment]
Hi Bryan,

Thank you for your interest in our work and for getting in touch.  So in that example, node 0 in graph 1 aligns to node 334 in graph 2.  (And for 334 in graph 1, you see that it aligns to 1120 in graph 2).  In this setup, each graph has 1135 nodes, so for each graph there are IDs 0-1134.  However, our implementation embeds the graphs jointly by combining the two graphs into one big adjacency matrix, so in that combined graph nodes 0 - 1134 represent nodes 0 - 1134 in graph 1, and nodes 1135-2269 in the combined graph represent nodes 0-1134 in graph 2.  Hope this helps, and sorry for any confusion you may have experienced.


Best,
Mark

**Comment by ChenBaiyang** [comment]
Hi Mark,
Thanks for your prompt reply!  It does help.

Regards,
Bryan
